#!/usr/bin/env sh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
#

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings

# set mouse follows focus mode (default: off)
yabai -m config mouse_follows_focus on

# set focus follows mouse mode (default: off, options: off, autoraise, autofocus)
yabai -m config focus_follows_mouse autoraise

# specify which display a newly created window should be managed in (default:
# default, options: default, focused, cursor)
yabai -m config window_origin_display focused

# New window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement second_child

# floating windows are always on top (default: off)
yabai -m config window_topmost off

# modify window shadows (default: on, options: on, off, float)
# example: show shadows only for floating windows
yabai -m config window_shadow on

# window opacity (default: off)
# example: render all unfocused windows with 90% opacity
yabai -m config window_opacity off
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.90

# window borders
yabai -m config window_border off
yabai -m config window_border_width 6
yabai -m config active_window_border_color 0xff775759
yabai -m config normal_window_border_color 0xff555555

# Floating point value between 0 and 1 (default: 0.5)
yabai -m config split_ratio 0.618 # golden ratio

# Balance the window tree upon change, so that all windows occupy the same area
# on or off (default: off)
yabai -m config auto_balance off

# set mouse interaction modifier key (default: fn, options: cmd, alt, shift, ctrl, fn)
yabai -m config mouse_modifier alt

# set modifier + left-click drag to move window (default: move)
yabai -m config mouse_action1 move

# set modifier + right-click drag to resize window (default: resize)
yabai -m config mouse_action2 resize

# action performed when a bsp-managed window is dropped in the center of some
# other bsp-managed window.
yabai -m config mouse_drop_action swap

# general space settings

# bsp or float (default: float, options: bsp, stack, float)
yabai -m config layout bsp

# Set all padding and gaps to 20pt (default: 0)
yabai -m config top_padding 0
yabai -m config bottom_padding 0
yabai -m config left_padding 0
yabai -m config right_padding 0
yabai -m config window_gap 0

# Custom app rules
yabai -m rule --add app="^Fantastical Helper$" manage=off border=off
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add label="Firfox PIP" app="^Firefox$" title="^(Picture-in-Picture)$" manage=off

# Destroy empty spaces when leaving them
yabai -m signal --add event=space_changed action='(RSINDEX=$(yabai -m query --spaces | jq -re ".[] | select(.id == $YABAI_RECENT_SPACE_ID).index") && [ "$(yabai -m query --spaces --space $RSINDEX | jq -re ".windows | length")" -eq 0 ] && yabai -m space $RSINDEX --destroy); /usr/local/bin/hs -c "YabaiBar:update()"'

# for when the current display changes
yabai -m signal --add event=display_changed action="/usr/local/bin/hs -c 'YabaiBar:update()'"

# display_changed does not trigger when the display changes
# but the front-most application stays the same
yabai -m signal --add event=application_front_switched action="/usr/local/bin/hs -c 'YabaiBar:update()'"

echo "yabai configuration loaded.."

# animations have been disabled to prevent a race with the window manager
# defaults write com.apple.finder DisableAllAnimations -bool true
# killall Finder

# re-enable with
# defaults delete com.apple.finder DisableAllAnimations
# killall Finder
